version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=db_data
      - MYSQL_ROOT_PASSWORD=ippenutt1
    ports:
      - '3306:3306'
    volumes:
      - go_vite_db:/var/lib/mysql
    expose:
      - '3306'
  app:
    build: ./server
    command: ./scripts/local-entrypoint.sh
    # command: go run main.go
    volumes:
      - './server:/app'
    ports:
      - 8080:8080
volumes:
  go_vite_db:
    driver: local